#ifndef __ENCODE_H__
#define __ENCODE_H__
#include "stm32f10x.h"

#define ENCODE_PHASEA_PIN GPIO_Pin_8
#define ENCODE_PHASEA_PORT GPIOF
#define ENCODE_PHASEA_PORT_SOURCE GPIO_PortSourceGPIOF
#define ENCODE_PHASEA_PIN_SOURCE GPIO_PinSource8
#define ENCODE_PHASEA_EXTI_LINE EXTI_Line8

#define ENCODE_PHASEB_PIN GPIO_Pin_9
#define ENCODE_PHASEB_PORT GPIOF
#define ENCODE_PHASEB_PORT_SOURCE GPIO_PortSourceGPIOF
#define ENCODE_PHASEB_PIN_SOURCE GPIO_PinSource9
#define ENCODE_PHASEB_EXTI_LINE EXTI_Line9

int32_t Get_Encode_Count(void);
void Encode_Init(void);
#endif
